### ISSUE TITLE
Add to metalsmith.io?

### ISSUE THREAD

**Issue by fidian** [ahdiaz/metalsmith-hbt-md#1]
Would you consider adding your useful plugin to the registry on the metalsmith.io web site?

https://github.com/metalsmith/metalsmith.io/blob/master/src/plugins.json

**Comment by ahdiaz** [comment]
Pull request opened, sorry for the delay.

**Comment by fidian** [comment]
Wonderful. Thanks! Closing this ticket because you've resolved my issue.

metalsmith/metalsmith.io#232
