### ISSUE TITLE
Errors in templates are difficult to detect

### ISSUE THREAD

**Issue by fidian** [ahdiaz/metalsmith-hbt-md#2]
Let's pretend I have a partial named `show-user-information.html` and in my mustache template I use the following:

    {{> show-user-info}}

I won't see the error that is generated because it is sent via `debug()` instead of `console.error()` or another mechanism. My rendered template will keep `{{> show-user-info}}` in it, just as though I may have mistyped the brackets or had invalid characters or something. The only way to see that I've done something wrong in my templates is to enable debug.

The way I have been solving this is to execute this line in my metalsmith config:

    debug(enable(debug.load() + " metalsmith-hbt-md");

Would you consider logging via `console.error()` or making such logging possible by passing a configuration option?

**Comment by ahdiaz** [comment]
I'm actually using an environment variable to enable the log output, like this:

    DEBUG=metalsmith* node index.js

Replace index.js by your script, of course. You should see the logs tagged with 'metalsmith-hbt-md'.
Do you think this would be enough for you? Please let me know.

**Comment by fidian** [comment]
That is just triggering the debug module in another way, so no. I would
expect a module to report errors unconditionally instead of silencing
output and disgusting problems as successes.

For instance, I was running the plugin over and over and had no clue that I
needed to enable debug output in order to see errors processing templates.
Debug output should help you track down software bugs, not enable messages
indicating invalid input to middleware.

**Comment by ahdiaz** [comment]
You're right, check if these changes works for you.

**Comment by fidian** [comment]
That works for me. Thanks for the update and for publishing so quickly.

**Comment by ahdiaz** [comment]
Great, closing this issue.
